default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vovimit_app_development

test:
  <<: *default
  database: vovimit_app_test

production:
  <<: *default
  database: vovimit_app_production
  username: vovimit_app
  password: <%= ENV['VOVIMIT_APP_DATABASE_PASSWORD'] %>
